services:
  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - endux_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  endux_backend:
    build:
      context: ./node-service
      dockerfile: Dockerfile
    container_name: endux_backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${POSTGRES_DB}?schema=public
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - endux_network
    volumes:
      - ./node-service:/usr/src/app
      - /usr/src/app/node_modules

  endux_frontend:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    container_name: endux_frontend
    ports:
      - "5173:5173"
    depends_on:
      - endux_backend
    networks:
      - endux_network
    volumes:
      - ./web-client:/app
      - /app/node_modules

  endux_ai:
    build:
      context: ./ai-services
      dockerfile: Dockerfile
    container_name: endux_ai
    ports:
      - "8000:8000"
    depends_on:
      - endux_backend
    networks:
      - endux_network
    volumes:
      - ./ai-services:/app

networks:
  endux_network:
    driver: bridge
